package com.learn.expensetracker.services;

import com.learn.expensetracker.domain.Category;
import com.learn.expensetracker.domain.User;
import com.learn.expensetracker.exceptions.EtBadRequestException;
import com.learn.expensetracker.exceptions.EtResourceNotFoundException;

import java.util.List;

public interface CategoryService {

    public List<Category> fetchAllCategories(Integer userId) throws EtResourceNotFoundException;
    public Category fetchCategoryById(Integer userId,Integer categoryId)  throws EtResourceNotFoundException;
    public Category addCategory(Integer userId,String title, String description) throws EtBadRequestException;//categoryId is autogenerated
    public void updateCategory(Integer userId,Integer categoryId,Category category) throws EtBadRequestException;
    public void removeCategoryWithAllTransactions(Integer userId, Integer categoryId)  throws EtResourceNotFoundException;
    public void updatePartialCategory(Integer userId, Integer categoryId,String title, String description);
}
