package com.learn.expensetracker.repositories;

import com.learn.expensetracker.domain.Category;
import com.learn.expensetracker.exceptions.EtBadRequestException;
import com.learn.expensetracker.exceptions.EtResourceNotFoundException;

import java.util.List;

public interface CategoryRepository {


    public List<Category> fetchAll(Integer userId) throws EtResourceNotFoundException;
    public Category fetchById(Integer userId,Integer categoryId) throws  EtResourceNotFoundException;
    public Integer create(Integer userId,String title, String description) throws EtBadRequestException;//categoryId is autogenerated
    public void update(Integer userId,Integer categoryId,Category category) throws EtBadRequestException;
    public void removeById(Integer userId, Integer categoryId) throws EtResourceNotFoundException;
    public void updatePartialOnlyTitle(Integer userId, Integer categoryId,String title);
    public void updatePartialOnlyDescription(Integer userId, Integer categoryId,String description);
}
